apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: as3-pv
spec:
  storageClassName: ""
  volumeName: pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo