apiVersion: apps/v1
kind: Deployment
metadata:
  name: as3-c1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as3-c1
  template:
    metadata:
      labels:
        app: as3-c1
    spec:
      volumes:
      - name: as3-pvc
        persistentVolumeClaim:
          claimName: as3-pvc
      containers:
      - name: as3-c1
        image: docker_image_url
        ports:
        - containerPort: 6000
        volumeMounts:
        - mountPath: "/Mayankkumar_PV_dir"
          name: as3-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: as3-c1-service
spec:
  type: LoadBalancer
  selector:
    app: as3-c1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000